[package]
name = "exponential-decay-histogram"
version = "0.1.15"
authors = ["Steven Fackler <sfackler@gmail.com>"]
description = "A histogram which exponentially weights in favor of recent values"
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sfackler/exponential-decay-histogram"
readme = "README.md"
categories = ["data-structures"]
keywords = ["metrics", "statistics"]

[[bench]]
name = "bench"
harness = false

[dependencies]
ordered-float = "5.0"
rand = "0.10"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-time = "1.1.0"
getrandom = { version = "0.4", features = ["wasm_js"] }

[dev-dependencies]
criterion = { version = "0.8", default-features = false }
wasm-bindgen-test = "0.3.58"
